### ISSUE TITLE
var skinClassName = 'Skin' + NativeClass.name; when running node server.js

### ISSUE THREAD

**Issue by miroamarillo** [sahat/tvshow-tracker#9]
npm WARN EPEERINVALID mongoskin@1.4.13 requires a peer of mongodb@~1.4 but none was installed.
npm WARN EPEERINVALID karma-jasmine@0.3.7 requires a peer of jasmine-core@* but none was installed.
npm WARN EPEERINVALID karma-phantomjs-launcher@0.2.3 requires a peer of phantomjs@>=1.9 but none was installed.

I get the previous after cloning the repo and running npm install.

If I run node server.js I get:

/tvshow-tracker/node_modules/mongoskin/lib/utils.js:33
  var skinClassName = 'Skin' + NativeClass.name;
                                          ^
TypeError: Cannot read property 'name' of undefined
    at makeSkinClass (/Users/miroamarillo/Sites/GitHub/tvshow-tracker/node_modules/mongoskin/lib/utils.js:33:43)
    at Object.<anonymous> (/Users/miroamarillo/Sites/GitHub/tvshow-tracker/node_modules/mongoskin/lib/grid.js:6:35)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/miroamarillo/Sites/GitHub/tvshow-tracker/node_modules/mongoskin/lib/db.js:22:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/miroamarillo/Sites/GitHub/tvshow-tracker/node_modules/mongoskin/lib/mongo_client.js:5:14)

Any idea how can I correct the issue?

Thanks!

**Comment by Leonab** [comment]
either remove the dependencies from package.json or add mongoskin etc to package.json via "npm install mongoskin --save". Though there's no need for mongoskin i reckon since mongoose is being used, try debugging yourself.

**Comment by jagroop** [comment]
getting  same error .. any luck ?? :/

**Comment by qramilq** [comment]
Try to reinstall agenda and mongoskin packages.
npm uninstall mongoskin --save
npm uninstall agenda --save
npm install mongoskin --save
npm install agenda --save
That helps for me
